http:
  host: "0.0.0.0"
  port: "8081"
  
aws:
  accesskey: "![ZL8Y5a+jJLBkPuCdDVKyTHNjqk05/gelqJNCmfRzQyc=]"
  secretkey: "![JEiETOOJk+ESogyRqFaUlBAAlYmEhl2eucFSshgvuSoNAxsOjBTjaYnvVqyJ4j1g]"
  regionendpoint: "us-east-1"
  S3:
    bucketname: "qbotica-processed"
    objectkey: "POACK20230203174015090.csv"
  putobject:
    bucketname: "blankupfile"
    objectkey: "POACK20230203174015090.csv"
